export default {
  GetPanelDetails: "GetPanelDetails",
  TryPassword: "TryPassword",
  GetPanelScripts: "GetPanelScripts",
  GetVmBackups: "GetVmBackups",
  GetVmBackupState: "GetVmBackupState",
  CancelBackup: "CancelBackup",
  ExecScript: "ExecScript",
  CancelScript: "CancelScript",
  SetNextBackupDate: "SetNextBackupDate",
  SetBackupSchedule: "SetBackupSchedule",
  SetBackupPeriodInterval: "SetBackupPeriodInterval",
  SetBackupSecondaryDst: "SetBackupSecondaryDst",
  GetRestoreBackups: "GetRestoreBackups",
  GetBackupRestores: "GetBackupRestores",
  RestoreBackup: "RestoreBackup",
  GetVmScreenshot: "GetVmScreenshot",
  GetMonitoringData: "GetMonitoringData",
  GetPlanTemplates: "GetPlanTemplates",
  EditPlanTemplate: "EditPlanTemplate",
  GetCdDrives: "GetCdDrives",
  InsertISO: "InsertISO",

  PowerOn: "PowerOn",
  PowerOff: "PowerOff",
  PowerReset: "PowerReset",
  VmSuspend: "VmSuspend",
  EjectISO: "EjectISO",
  Delete: "Delete",
  Deploy: "Deploy",
};
